// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kworking.API.Data;

#nullable disable

namespace kworking.API.Migrations
{
    [DbContext(typeof(KworkingDbContext))]
    [Migration("20260519213309_AddServicesAndSubscriptions")]
    partial class AddServicesAndSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kworking.API.Models.Booking", b =>
                {
                    b.Property<int>("Id_booking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_booking"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_client")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_tariff")
                        .HasColumnType("integer");

                    b.Property<int>("Id_workPlace")
                        .HasColumnType("integer");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServicesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id_booking");

                    b.HasIndex("Id_client");

                    b.HasIndex("Id_tariff");

                    b.HasIndex("Id_workPlace");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("kworking.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("kworking.API.Models.Payment", b =>
                {
                    b.Property<int>("Id_payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_payment"));

                    b.Property<int?>("Id_booking")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_client")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SubscriptionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_payment");

                    b.HasIndex("Id_booking");

                    b.HasIndex("Id_client");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("kworking.API.Models.Tariff", b =>
                {
                    b.Property<int>("Id_tariff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_tariff"));

                    b.Property<int?>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsService")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ValidDays")
                        .HasColumnType("integer");

                    b.HasKey("Id_tariff");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("kworking.API.Models.User", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_user"));

                    b.Property<int?>("Id_client")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id_user");

                    b.HasIndex("Id_client");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("kworking.API.Models.WorkPlace", b =>
                {
                    b.Property<int>("Id_workplace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_workplace"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_workplace");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkPlaces");
                });

            modelBuilder.Entity("kworking.API.Models.Booking", b =>
                {
                    b.HasOne("kworking.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_client")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kworking.API.Models.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("Id_tariff")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kworking.API.Models.WorkPlace", "WorkPlace")
                        .WithMany()
                        .HasForeignKey("Id_workPlace")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tariff");

                    b.Navigation("WorkPlace");
                });

            modelBuilder.Entity("kworking.API.Models.Payment", b =>
                {
                    b.HasOne("kworking.API.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("Id_booking")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kworking.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_client")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("kworking.API.Models.User", b =>
                {
                    b.HasOne("kworking.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_client")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
